<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'Admin','Shopping',
        'DoctrineModule',
        'DoctrineORMModule',
        'OTNCore',
        'JVFlashMessenger',
        //'ZendDeveloperTools', // Mostrar barra de Doctrine e outros no rodapé
        'Home',  // Pega o Layout de pagina deste !
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
        ),
        'config_glob_paths' => array(
            'config/autoload/{{,*.}global,{,*.}local}.php',
        ),
    ),
);
