<?= $this->render('orion/header'); ?>
<link rel="stylesheet" href="//static.wmobjects.com.br/webstore/style/product.min.css">
<link rel="stylesheet" href="//static.wmobjects.com.br/webstore/style/search.min.css">
<body class="webstore search">
    <?= $this->render('orion/b_principal'); ?>

       <div style="height: 20px;"></div>

<div id="main" class="clearfix">
    
    
    <h1 class="search-title">Resultados de busca para "..."</h1>
        
    
        

    
    
    
    </div>


    <!--rodape#################################-->
    <footer>
        <div class="go-to-top-container">
            <div class="go-to-top">
            </div>
        </div>

        <div class="go-to-top-container">
            <div class="go-to-top hide">
            </div>
        </div>

        <?= $this->render('orion/atendimento'); ?>

        <?= $this->render('orion/forma_pagamento'); ?>

        <?= $this->render('orion/sobre_loja'); ?> 
    </footer>
</div>
</div>

<?= $this->render('orion/footer'); ?>