<div class="shelf-container">
    <section>
        <h2 class="shelf-title">Escolhemos para você</h2>
        <ul class="shelf-itens clearfix  two-rows" itemscope="" itemtype="http://schema.org/ItemList">
            <li class="shelf-item item-0 with-buy-box" itemprop="itemListElement" itemscope itemtype="http://schema.org/Product" data-productId="3086266" data-available="true" data-hastree=''>
                <figure><a href="/smart-tv-led-hd-32-lg-32lf585b-3-hdmi-3-usb-wi-fi-integrado/3086266/pr" title="Smart TV LED HD 32&quot; LG 32LF585B 3 HDMI 3 USB Wi-fi integrado" itemprop="url"><img src="//static.wmobjects.com.br/webstore/images/global/spacer.gif" class="lazy-image loading" data-src="http://static.wmobjects.com.br/imgres/arquivos/ids/4317490-220-220/smart-tv-led-hd-32--lg-32lf585b-3-hdmi-3-usb-wi-fi-integrado.jpg" alt="Smart TV LED HD 32&quot; LG 32LF585B 3 HDMI 3 USB Wi-fi integrado" itemprop="image" width="220" height="220"></a></figure>
                <div class="inner-content">
                    <a href="/smart-tv-led-hd-32-lg-32lf585b-3-hdmi-3-usb-wi-fi-integrado/3086266/pr" class="product-link">
                        <span class="product-title" itemprop="name">Smart TV LED HD 32&quot; LG 32LF585B 3 HDMI 3 USB Wi-fi integrado</span>
                        <p class="shelf-price"  itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                            <span class="payment-price-old"><span class="label">De: </span><del>R$ 1.349,00</del></span>
                            <span class="payment-sell">
                                <span class="label">Por</span><span class="payment-currency">R$ </span>
                                <meta itemprop="priceCurrency" content="BRL">
                                <span class="payment-price" itemprop="price"><strong><span class="int">1.214</span><span class="dec">,10</span></strong></span><span class="tooltip-container"></span>
                            </span>
                            <span class="payment-installment"><span class="payment-installment-amount" itemprop="itemCondition">10x <span>de </span><span class="payment-installment-currency"></span><span class="payment-installment-price">R$ 121,41 </span><span class="payment-installment-condition">sem juros</span></span></span>
                        </p>
                    </a>
                    <div class="button-container"><button type="button" class="buy-button btn btn-success hidden" data-sku="1220560" data-product="3086266" data-seller="1" data-available="true" data-skipservice="true"><span class="icon"></span></button></div>
                </div>
            </li>
                                           
        </ul>
    </section>
</div>