<!-- Include de JS############# -->
<?php
echo $this->headScript()
        //->appendFile('/js/orion/jquery-2.0.3.min.js')
        ->appendFile('/js/orion/global.min.js')
        ->appendFile('/js/orion/home.min.js')
        ->appendFile('/js/orion/loader.js')
        ; 
?>
<script src="//static.wmobjects.com.br/webstore/js/department.min.js"></script>
<script type="text/javascript">_satellite.pageBottom();</script>
</body>
</html>