<div class="footer-flags clearfix">
<div class="flags-cards">
<strong class="flags-title">Formas de pagamento</strong>
<ul class="flag-card-list">
    <li style="padding-left: 0px; padding-top: 10px;">        
        <?php
//        foreach ($formas_pagamento as $img_id) {        
//            
//            echo '<img src="/images/img'.$img_id['img_id'].'.'.$img_id['ext'].'"  height="40">';        
//        }
        ?>    
</li>

</ul>
</div>
<div class="flags-services">
<strong class="flags-title">Site seguro</strong>
<ul class="flag-services-list">
<li>
<img src="/images/security_label.png">
</li>

</ul>
</div>

</div>