<?= $this->render('orion/header'); ?>

<body class="webstore home" > 
    
  
    <?= $this->render('orion/b_principal'); ?>

    <?= $this->render('orion/barra_categoria'); ?>    
    <?= $this->render('orion/banner_principal'); ?>
   
    <?= $this->render('orion/newsletter'); ?>
    
   
</html>
    
    <div id="main" class="clearfix">
        <div class="content">
            <div class="main-content clearfix">

                <?= $this->render('orion/para_voce'); ?>    
               
                <?= $this->render('orion/produto_categoria'); ?>               

            </div>

        </div>
    </div>
<!--<iframe scrolling="no" style="width:100%;scroll:none;border:0;" class="mfp-iframe" name="iframeLogin" id="iframeLogin" src="https://www2.walmart.com.br/api/webstore/auth/login?modal=true"></div></iframe>-->

    <!--rodape#################################-->
    <footer>
        <div class="go-to-top-container">
            <div class="go-to-top">
            </div>
        </div>

        <div class="go-to-top-container">
            <div class="go-to-top hide">
            </div>
        </div>

        <?= $this->render('orion/atendimento'); ?>

        <?= $this->render('orion/forma_pagamento'); ?>

        <?= $this->render('orion/sobre_loja'); ?> 
    </footer>
</div>
</div>

<?= $this->render('orion/footer'); ?>