<span ng-controller="cartActionsParavc">
<?php 



if(!$para_vc){   
} else {

?>
<!--Inicio Slide prateleira para voce ####################-->
<div class="cd-dvd-blu-ray home-list clearfix">
<nav class="left-nav">
<h2 class="menu-title">
<a class="menu-title-link" href="#"></span>Para Você</a></h2>

   

<ul class="menu-items">    
    <div style=" border: 1px dotted #ccc; padding-left: 12px; height: 170px; color: #666;">
        
        <div style=" position: relative; float: left; width: 150px; height: 170px; bottom: 0px; margin-right: 12px;">
            <?php
            $i = 0;
            $img_rand = array();
            foreach ($para_vc as $key => $pvc_data) {
                    
                $imagem = 'img'.$pvc_data['img_id'].'.'.$pvc_data['ext'];
                $img_rand[] = $imagem;
            }
            
            $rand_key = array_rand($img_rand,1);          
            
            $imagem_para_vc = $img_rand[$rand_key];
            ?>
            
            <img src="images/<?php  echo $imagem_para_vc; ?>" width="147" height="148">
            
        </div> 
        
        <br>
        Você visitou e separamos mais ofertas para você.
        
    </div>
</ul>

</nav>

<!--Horizontal Wrap###############-->
<div class="shelf-home shelf-container shelf-horizontal  two-rows">
<div class="shelf-itens carousel-shelf-horizontal arrow-big clearfix">    
    <?php
        
        $i = 0;       
       
        foreach ($para_vc as $key => $pvc_data) {        
         
         $produto_id = $pvc_data['id'];
         $produto_nome = $pvc_data['nome'];
         $imagem = 'img'.$pvc_data['img_id'].'.'.$pvc_data['ext'];
        
      
            
            
            $preco_promo = substr($pvc_data['precopromocional'], 0, -3);
            $preco_promo_dec = substr($pvc_data['precounitario'], -2);
            
            #preco normal###################
            $preco_ok = $pvc_data['precounitario'];
            ################################
            
            
            
            if(empty($preco_promo)){      
            
                
            $preco_promo = substr($pvc_data['precopromocional'], 0, -3);
            $preco_promo_dec = substr($pvc_data['precounitario'], -2);
            $hide = 'style="display:none"';
                
            } else {
                
                $hide = '';                
            }
            
         $url_seo = filterUrl2($produto_nome, '-');
            
         echo '             
                <!--item #########################-->
                    <div class="shelf-item with-buy-box clearfix" data-productId="2987341" data-available="true" data-hastree="" data-

                    skipservice="true">

                    <figure><a href="produto/'.$produto_id.'/'.$url_seo.'" title="Testes Ótimo negócio template">
                        <img class="lazyOwl" data-src="images/'.$imagem.'" alt="Ótimo negocio teste" width="130" 

                    height="130"></a>
                    </figure>

                    <div class="inner-content">
                    <div class="left-align">
                    <a href="produto/'.$produto_id.'/'.$url_seo.'">
                    <span class="product-title" style="height:50px;">'.$produto_nome.'</span>
                    <p class="shelf-price"  itemprop="offers" itemscope itemtype="http://schema.org/Offer">

                    <span class="payment-price-old">
                    <span class="label" '.$hide.'>De: </span>

                    <del '.$hide.'>R$ '.$preco_ok.'</del></span>

                    <span class="payment-sell">
                    <span class="label">Por</span><span class="payment-currency">R$ </span>
                    <meta itemprop="priceCurrency" content="BRL">
                    <span class="payment-price" itemprop="price">
                    <strong>
                    <span class="int">'.$preco_promo.'</span><span class="dec">,'.$preco_promo_dec.'</span>
                    </strong></span>

                    <span class="tooltip-container"></span>
                    </span>

                    <span class="payment-installment">
                    <span class="payment-installment-amount" itemprop="itemCondition">à vista</span>
                    </span></p>

                    </a>
                    </div>

                    <div class="stickers">
                    <ul>
                    <li class="stamp-top"></li>
                    <li class="stamp-middle"></li>
                    <li class="stamp-bottom"></li>
                    </ul>
                    </div>

                    <div class="button-container">
                    
                    
<button type="button" name="test[]" class="buy-button btn btn-success hidden" ng-click="addCart('.$produto_id.') " >
            <span class="icon"></span>
            </button>

                   


                    </div>
                    </div>
                    </div>
                <!--/ item################-->
             ';
        $i++;
      }    
    
    ?>
 
</div>
</div>

<!--/horizontal Wrap################-->




</div>
<!--/Slide prateleira para voce####################-->
<?php } function filterUrl2($string, $slug = false) {
          $string = strtolower($string);         
          $ascii['a'] = range(224, 230);
          $ascii['e'] = range(232, 235);
          $ascii['i'] = range(236, 239);
          $ascii['o'] = array_merge(range(242, 246), array(240, 248));
          $ascii['u'] = range(249, 252);          
          $ascii['b'] = array(223);
          $ascii['c'] = array(231);
          $ascii['d'] = array(208);
          $ascii['n'] = array(241);
          $ascii['y'] = array(253, 255);
          foreach ($ascii as $key=>$item) {
            $acentos = '';
            foreach ($item AS $codigo) $acentos .= chr($codigo);
            $troca[$key] = '/['.$acentos.']/i';
          }
          $string = preg_replace(array_values($troca), array_keys($troca), $string);
        
          if ($slug) {
           
            $string = preg_replace('/[^a-z0-9]/i', $slug, $string);
          
            $string = preg_replace('/' . $slug . '{2,}/i', $slug, $string);
            $string = trim($string, $slug);
          }
          return $string;
        }?>

</span>
<script>
        angular.module('ui.bootstrap.app').controller('cartActionsParavc', function ($scope, $http) {
             
                $scope.addCart = function (data) {
                    
                  $scope.prod_id = data;
                 
                  $('#num_itens').css('display', 'inline-block');                 
                 
                    var request = $http({
                        method: "post",
                        url: "/cart/add",
                        data: {
                            prod_id: $scope.prod_id,
                            
                        },
                        headers: {'Content-Type': 'application/x-www-form-urlencoded'}
                    });                    
                    
                    /* Check whether the HTTP Request is successful or not. */
                    request.success(function (data) {                       
                        
                        $("span#num_itens").load("/cart/qtd");
                        $("div#cart").load("/cart/queryCart");                    
            
                    });
                    request.error(function (data) {
                         document.getElementById("messageCadastrar1").textContent = "Houve um problema ["+data+"]";
                    });
                };
            });
            
    
    
    </script>